version: '3'

services:
  mysql:
    image: mysql:5.7.33
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=springcache
      - MYSQL_PASSWORD=springcache
      - MYSQL_DATABASE=springcache